## Dataset description

The dataset is from the U.S. Small Business Administration (SBA) The U.S. SBA was founded in 1953 on the principle of promoting and assisting small enterprises in the U.S. credit market (SBA Overview and History, US Small Business Administration (2015)). Small businesses have been a primary source of job creation in the United States; therefore, fostering small business formation and growth has social benefits by creating job opportunities and reducing unemployment. There have been many success stories of start-ups receiving SBA loan guarantees such as FedEx and Apple Computer. However, there have also been stories of small businesses and/or start-ups that have defaulted on their SBA-guaranteed loans.  
More info on the original dataset: https://www.kaggle.com/mirbektoktogaraev/should-this-loan-be-approved-or-denied

## Preparation

In [1]:
import pandas as pd
pd.set_option('display.max_columns', 1500)

import warnings
warnings.filterwarnings('ignore')

#Extend cell width
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:80% !important; }</style>"))

### Load data

In [3]:
data = pd.read_csv('SBA_loans_project_1.zip')

In [4]:
print("Data shape:", data.shape)

Data shape: (809247, 21)

**Review dataset**

In [5]:
desc_df = describe_more(data)
desc_df

,A_Variable,Levels,Datatype,Min Length,Max Length,Level_Values
0,index,809247,int64,1,6,"{0: 1, 539491: 1, 539493: 1, 539494: 1, 539495..."
1,City,31320,object,1,30,"{'LOS ANGELES': 10372, 'HOUSTON': 9260, 'NEW Y..."
2,State,51,object,2,3,"{'CA': 117341, 'TX': 63425, 'NY': 51877, 'FL':..."
3,Zip,32731,int64,1,5,"{10001: 841, 90015: 830, 93401: 729, 90010: 65..."
4,Bank,5716,object,3,30,"{'BANK OF AMERICA NATL ASSOC': 78111, 'WELLS F..."
5,BankState,55,object,2,3,"{'CA': 106293, 'NC': 71557, 'IL': 59258, 'OH':..."
6,NAICS,1307,int64,1,6,"{0: 181845, 722110: 25217, 722211: 17476, 8111..."
7,Term,407,int64,1,3,"{84: 207228, 60: 80965, 240: 77385, 120: 69852..."
8,NoEmp,581,int64,1,4,"{1: 138836, 2: 124470, 3: 81466, 4: 66306, 5: ..."
9,NewExist,3,float64,3,3,"{1.0: 580478, 2.0: 227709, 0.0: 932}"
10,CreateJob,234,int64,1,4,"{0: 566148, 1: 56789, 2: 52162, 3: 25945, 4: 1..."
11,RetainedJob,345,int64,1,4,"{0: 396287, 1: 79893, 2: 69149, 3: 44941, 4: 3..."
12,FranchiseCode,2684,int64,1,5,"{1: 574731, 0: 187961, 78760: 3043, 68020: 173..."
13,UrbanRural,3,int64,1,1,"{1: 423681, 0: 290804, 2: 94762}"
14,RevLineCr,16,object,1,3,"{'N': 378424, '0': 231967, 'Y': 181011, 'T': 1..."
15,LowDoc,8,object,1,3,"{'N': 704515, 'Y': 99339, '0': 1343, 'C': 681,..."
16,DisbursementGross,110579,object,6,15,"{'$50,000.00 ': 39328, '$100,000.00 ': 33116, ..."
17,BalanceGross,13,object,6,12,"{'$0.00 ': 809235, '$41,509.00 ': 1, '$115,820..."
18,GrAppv,20724,object,8,14,"{'$50,000.00 ': 62264, '$25,000.00 ': 46168, '..."
19,SBA_Appv,35896,object,8,14,"{'$25,000.00 ': 44418, '$12,500.00 ': 36115, '..."
20,MIS_Status,2,object,3,6,"{'P I F': 665576, 'CHGOFF': 141849}"

## Dataset preparation and clean-up

- Replace encode Na/Null values
- Convert the strings styled as '$XXXX.XX' to float values. Columns = ['DisbursementGross', 'BalanceGross', 'GrAppv', 'SBA_Appv']
- Convert MIS_Status to 0/1. Make value "CHGOFF" as 1

In [6]:
#Replacing null values
null_cols = data.columns[data.isnull().any()]
# Replace null values in numerical columns with the mean of the column
for col in data.select_dtypes(include='number').columns:
    if col in null_cols:
        data[col].fillna(data[col].mean(), inplace=True)
# Replace null values in categorical columns with the mode of the column
for col in data.select_dtypes(include='object').columns:
    if col in null_cols:
        data[col].fillna(data[col].mode()[0], inplace=True)

In [7]:
#Converting in to float
c1=['DisbursementGross', 'BalanceGross', 'GrAppv', 'SBA_Appv']
data[c1] = data[c1].replace('[\$,]', '', regex=True).astype(float)
data['MIS_Status'] = (data['MIS_Status'] == "CHGOFF").astype(int)

In [8]:
data.isnull().any() #there are no null values

index                False
City                 False
State                False
Zip                  False
Bank                 False
BankState            False
NAICS                False
Term                 False
NoEmp                False
NewExist             False
CreateJob            False
RetainedJob          False
FranchiseCode        False
UrbanRural           False
RevLineCr            False
LowDoc               False
DisbursementGross    False
BalanceGross         False
GrAppv               False
SBA_Appv             False
MIS_Status           False
dtype: bool

In [9]:
describe = describe_more(data)
describe

,A_Variable,Levels,Datatype,Min Length,Max Length,Level_Values
0,index,809247,int64,1,6,"{0: 1, 539491: 1, 539493: 1, 539494: 1, 539495..."
1,City,31320,object,1,30,"{'LOS ANGELES': 10397, 'HOUSTON': 9260, 'NEW Y..."
2,State,51,object,2,2,"{'CA': 117353, 'TX': 63425, 'NY': 51877, 'FL':..."
3,Zip,32731,int64,1,5,"{10001: 841, 90015: 830, 93401: 729, 90010: 65..."
4,Bank,5716,object,3,30,"{'BANK OF AMERICA NATL ASSOC': 79516, 'WELLS F..."
5,BankState,55,object,2,2,"{'CA': 107704, 'NC': 71557, 'IL': 59258, 'OH':..."
6,NAICS,1307,int64,1,6,"{0: 181845, 722110: 25217, 722211: 17476, 8111..."
7,Term,407,int64,1,3,"{84: 207228, 60: 80965, 240: 77385, 120: 69852..."
8,NoEmp,581,int64,1,4,"{1: 138836, 2: 124470, 3: 81466, 4: 66306, 5: ..."
9,NewExist,4,float64,3,18,"{1.0: 580478, 2.0: 227709, 0.0: 932, 1.2802764..."
10,CreateJob,234,int64,1,4,"{0: 566148, 1: 56789, 2: 52162, 3: 25945, 4: 1..."
11,RetainedJob,345,int64,1,4,"{0: 396287, 1: 79893, 2: 69149, 3: 44941, 4: 3..."
12,FranchiseCode,2684,int64,1,5,"{1: 574731, 0: 187961, 78760: 3043, 68020: 173..."
13,UrbanRural,3,int64,1,1,"{1: 423681, 0: 290804, 2: 94762}"
14,RevLineCr,16,object,1,1,"{'N': 382518, '0': 231967, 'Y': 181011, 'T': 1..."
15,LowDoc,8,object,1,1,"{'N': 706834, 'Y': 99339, '0': 1343, 'C': 681,..."
16,DisbursementGross,110579,float64,3,10,"{50000.0: 39328, 100000.0: 33116, 25000.0: 247..."
17,BalanceGross,13,float64,3,8,"{0.0: 809235, 41509.0: 1, 115820.0: 1, 84617.0..."
18,GrAppv,20724,float64,5,9,"{50000.0: 62264, 25000.0: 46168, 100000.0: 459..."
19,SBA_Appv,35896,float64,5,9,"{25000.0: 44418, 12500.0: 36115, 5000.0: 27999..."
20,MIS_Status,2,int32,1,1,"{0: 667398, 1: 141849}"

## Categorical and numerical variables encoding

In [10]:
df=data.copy()
do=data.copy() #df and do  unchanged datset used in further code

In [11]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
# Initialize OneHotEncoder
ohe = OneHotEncoder()

# Fit and transform the categorical column using OneHotEncoder
ohe_results = ohe.fit_transform(data[['LowDoc']]).toarray()

# Create a new dataframe with the encoded columns
encoded_data = pd.DataFrame(ohe_results, columns=ohe.get_feature_names(['LowDoc']))

# Concatenate the original dataframe with the encoded dataframe
data_encoded = pd.concat([data, encoded_data], axis=1)

# Drop the original categorical column
data_encoded.drop(['LowDoc'], axis=1, inplace=True)

data=data_encoded

In [12]:
#Target Encoding
import category_encoders as ce
target_cols = [col for col in data.columns if data[col].dtype=='object' and col !="LowDoc" and col != 'MIS_Status']
target_encoder = ce.TargetEncoder(cols=target_cols)
data = target_encoder.fit_transform(data, data['MIS_Status'])
data['MIS_Status'] = data.pop('MIS_Status')

In [13]:
data

,index,City,State,Zip,Bank,BankState,NAICS,Term,NoEmp,NewExist,CreateJob,RetainedJob,FranchiseCode,UrbanRural,RevLineCr,DisbursementGross,BalanceGross,GrAppv,SBA_Appv,LowDoc_0,LowDoc_1,LowDoc_A,LowDoc_C,LowDoc_N,LowDoc_R,LowDoc_S,LowDoc_Y,MIS_Status
0,0,0.172222,0.197566,21060,0.000000e+00,0.382373,811111,240,7,1.0,6,7,1,1,0.149590,743000.0,0.0,743000.0,743000.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0
1,1,0.118343,0.123196,53095,2.738090e-01,0.222215,722410,240,20,1.0,0,0,1,0,0.145047,137000.0,0.0,137000.0,109737.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0
2,2,0.149938,0.184597,92128,2.681605e-01,0.180539,0,120,2,1.0,0,0,1,0,0.149590,280000.0,0.0,280000.0,210000.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0
3,3,0.139818,0.128058,1570,3.756369e-02,0.065488,621310,84,7,1.0,0,0,1,1,0.149590,144500.0,0.0,144500.0,122825.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0
4,4,0.178832,0.153553,64804,1.749850e-01,0.158467,0,60,2,2.0,0,0,1,0,0.145047,52500.0,0.0,52500.0,42000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
809242,809242,0.236211,0.179758,70808,1.091002e-11,0.107972,0,240,24,2.0,24,0,38605,0,0.145047,749000.0,0.0,750000.0,750000.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0
809243,809243,0.165482,0.206788,29611,1.180762e-01,0.097218,0,72,5,1.0,0,0,1,0,0.145047,75000.0,0.0,75000.0,67500.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0
809244,809244,0.090759,0.117137,55114,1.363636e-01,0.076748,424990,120,31,1.0,0,31,1,1,0.149590,216900.0,0.0,216900.0,162675.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0
809245,809245,0.146554,0.166270,35401,1.446159e-01,0.130455,0,120,4,2.0,0,0,1,1,0.145047,75000.0,0.0,75000.0,60000.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0
809246,809246,0.140000,0.184597,90670,1.486414e-01,0.140081,313210,300,35,1.0,0,0,1,0,0.149590,756000.0,0.0,756000.0,567000.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0

# Model Training

See Project summary for types of models

In [14]:
import h2o
from h2o.estimators.glm import H2OGeneralizedLinearEstimator
from h2o.grid.grid_search import H2OGridSearch
from sklearn.metrics import f1_score
import pandas as pd

# Initialize H2O
h2o.init()

# Load data
dt = data.copy()
d1 = h2o.H2OFrame(dt)

# Split data into train, validation, and test sets
train, valid, test = d1.split_frame([0.7, 0.15], seed=1234)

# Define hyperparameters and regularization options
hyper_params = {
    "alpha": [0.1, 0.5, 0.9],
    "lambda": [0.001, 0.01, 0.1]
}

# Define search criteria
search_criteria = {
    "strategy": "RandomDiscrete",
    "max_models": 10,
    "seed": 1234
}

# Define GLM model
model = H2OGeneralizedLinearEstimator(
    family="binomial",
    nfolds=5,
    fold_assignment="Modulo",
    keep_cross_validation_predictions=True,
    seed=1234
)

# Perform grid search for best model
grid = H2OGridSearch(model, hyper_params, search_criteria=search_criteria)
grid.train(x=train.names[:-1], y=train.names[-1], training_frame=train, validation_frame=valid)

# Get best model and its performance on validation and test sets
best_model = grid.get_grid()[0]
valid_perf = best_model.model_performance(valid)
test_perf = best_model.model_performance(test)

# Find the optimal threshold using F1 score on validation set
f1_scores = valid_perf.F1(thresholds=[0.5])
f1_df = pd.DataFrame(f1_scores, columns=["Threshold", "F1"])
optimal_threshold = f1_df[f1_df["F1"] == f1_df["F1"].max()]["Threshold"].item()

# Evaluate the best model on validation and test sets using the optimal threshold
valid_pred = best_model.predict(valid).as_data_frame()["p1"]
valid_pred_binary = [1 if pred >= optimal_threshold else 0 for pred in valid_pred]
valid_f1 = f1_score(valid.as_data_frame(True)["MIS_Status"], valid_pred_binary)

test_pred = best_model.predict(test).as_data_frame()["p1"]
test_pred_binary = [1 if pred >= optimal_threshold else 0 for pred in test_pred]
test_f1 = f1_score(test.as_data_frame(True)["MIS_Status"], test_pred_binary)

print("Best Model:\n", best_model)

Checking whether there is an H2O instance running at http://localhost:54321 . connected.

--------------------------  -----------------------------
H2O_cluster_uptime:         22 hours 26 mins
H2O_cluster_timezone:       America/Chicago
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.38.0.4
H2O_cluster_version_age:    2 months and 28 days
H2O_cluster_name:           H2O_from_python_haric_ngzpp4
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    511.7 Mb
H2O_cluster_total_cores:    16
H2O_cluster_allowed_cores:  16
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://localhost:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
Python_version:             3.9.13 final
--------------------------  -----------------------------

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
glm Grid Build progress: |███████████████████████████████████████████████████████| (done) 100%
Could not find exact threshold 0.5; using closest threshold found 0.4996675153119627.
glm prediction progress: |███████████████████████████████████████████████████████| (done) 100%
glm prediction progress: |███████████████████████████████████████████████████████| (done) 100%
Best Model:
 Model Details
=============
H2OGeneralizedLinearEstimator : Generalized Linear Modeling
Model Key: Grid_GLM_py_2_sid_8f15_model_python_1680395157827_991_model_8


GLM Model: summary
    family    link    regularization                              number_of_predictors_total    number_of_active_predictors    number_of_iterations    training_frame
--  --------  ------  ------------------------------------------  ----------------------------  -----------------------------  ----------------------  ----------------
    binomial  logit   Elastic Net (alpha = 0.1, lambda = 0.001 )  26                            24                             5                       py_2_sid_8f15

ModelMetricsBinomialGLM: glm
** Reported on train data. **

MSE: 0.09988260308393383
RMSE: 0.3160420906840319
LogLoss: 0.33795411554285903
AUC: 0.8556057766622698
AUCPR: 0.6113258971154077
Gini: 0.7112115533245396
Null degrees of freedom: 566622
Residual degrees of freedom: 566598
Null deviance: 526482.4395127706
Residual deviance: 382985.13387816714
AIC: 383035.13387816714

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.3191528515733189
       0       1       Error    Rate
-----  ------  ------  -------  ------------------
0      421865  45287   0.0969   (45287.0/467152.0)
1      37142   62329   0.3734   (37142.0/99471.0)
Total  459007  107616  0.1455   (82429.0/566623.0)

Maximum Metrics: Maximum metrics at their respective thresholds
metric                       threshold    value     idx
---------------------------  -----------  --------  -----
max f1                       0.319153     0.60196   195
max f2                       0.190775     0.677836  261
max f0point5                 0.40601      0.626292  157
max accuracy                 0.40601      0.868692  157
max precision                0.705658     0.827291  58
max recall                   0.000576855  1         399
max specificity              0.990389     0.999919  0
max absolute_mcc             0.350743     0.516391  180
max min_per_class_accuracy   0.207696     0.783565  251
max mean_per_class_accuracy  0.230339     0.785541  239
max tns                      0.990389     467114    0
max fns                      0.990389     99466     0
max fps                      0.000576855  467152    399
max tps                      0.000576855  99471     399
max tnr                      0.990389     0.999919  0
max fnr                      0.990389     0.99995   0
max fpr                      0.000576855  1         399
max tpr                      0.000576855  1         399

Gains/Lift Table: Avg response rate: 17.56 %, avg score: 17.56 %
group    cumulative_data_fraction    lower_threshold    lift       cumulative_lift    response_rate    score        cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain      cumulative_gain    kolmogorov_smirnov
-------  --------------------------  -----------------  ---------  -----------------  ---------------  -----------  --------------------------  ------------------  --------------  -------------------------  --------  -----------------  --------------------
1        0.0100014                   0.798227           4.60273    4.60273            0.808011         0.857584     0.808011                    0.857584            0.0460335       0.0460335                  360.273   360.273            0.0437045
2        0.020001                    0.726544           4.78551    4.69411            0.840099         0.760373     0.824054                    0.808983            0.0478531       0.0938867                  378.551   369.411            0.0896182
3        0.0300005                   0.674795           4.68095    4.68972            0.821744         0.69937      0.823284                    0.772447            0.0468076       0.140694                   368.095   368.972            0.134264
4        0.0400001                   0.632148           4.46681    4.634              0.784151         0.653179     0.813501                    0.742631            0.0446663       0.185361                   346.681   363.4              0.176312
5        0.0500015                   0.594105           4.2881     4.56481            0.752779         0.61273      0.801355                    0.716648            0.0428869       0.228247                   328.81    356.481            0.2162
6        0.100001                    0.459185           3.59403    4.07943            0.630934         0.521196     0.716146                    0.618924            0.179701        0.407948                   259.403   307.943            0.373518
7        0.150001                    0.368503           2.80787    3.65558            0.492923         0.411307     0.641739                    0.549719            0.140393        0.548341                   180.787   265.558            0.483159
8        0.200001                    0.30614            1.89906    3.21645            0.33338          0.335962     0.56465                     0.49628             0.0949523       0.643293                   89.9056   221.645            0.537683
9        0.3                         0.217272           1.26922    2.56738            0.222812         0.258262     0.450705                    0.416941            0.126921        0.770214                   26.9221   156.738            0.570337
10       0.4                         0.15562            0.753892   2.11401            0.132346         0.184879     0.371116                    0.358926            0.0753888       0.845603                   -24.6108  111.401            0.540486
11       0.500001                    0.110841           0.459224   1.78305            0.080617         0.131859     0.313015                    0.313512            0.0459229       0.891526                   -54.0776  78.3049            0.474893
12       0.6                         0.0770282          0.278374   1.53227            0.0488687        0.0934442    0.268991                    0.276834            0.0278373       0.919363                   -72.1626  53.2271            0.387365
13       0.7                         0.0450036          0.232632   1.34661            0.0408387        0.0609231    0.236398                    0.24599             0.0232631       0.942626                   -76.7368  34.661             0.294289
14       0.799999                    0.0110635          0.312153   1.2173             0.0547986        0.028039     0.213698                    0.218746            0.0312151       0.973842                   -68.7847  21.7303            0.210859
15       0.899999                    0.00176278         0.211118   1.10551            0.0370619        0.00459383   0.194072                    0.194952            0.0211117       0.994953                   -78.8882  10.5505            0.115173
16       1                           1.55719e-15        0.0504663  1                  0.0088594        0.000939918  0.175551                    0.17555             0.0050467       1                          -94.9534  0                  0

ModelMetricsBinomialGLM: glm
** Reported on validation data. **

MSE: 0.09919389071896807
RMSE: 0.3149506163178095
LogLoss: 0.33636126999901966
AUC: 0.8551204186995636
AUCPR: 0.6054161718195485
Gini: 0.7102408373991271
Null degrees of freedom: 121396
Residual degrees of freedom: 121372
Null deviance: 111886.54026051765
Residual deviance: 81666.49818447312
AIC: 81716.49818447312

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.3253499277287662
       0      1      Error    Rate
-----  -----  -----  -------  ------------------
0      90977  9403   0.0937   (9403.0/100380.0)
1      8044   12973  0.3827   (8044.0/21017.0)
Total  99021  22376  0.1437   (17447.0/121397.0)

Maximum Metrics: Maximum metrics at their respective thresholds
metric                       threshold    value     idx
---------------------------  -----------  --------  -----
max f1                       0.32535      0.597931  191
max f2                       0.196921     0.677687  259
max f0point5                 0.433798     0.623031  143
max accuracy                 0.433798     0.869659  143
max precision                0.748861     0.825304  41
max recall                   0.000480518  1         399
max specificity              0.991528     0.99993   0
max absolute_mcc             0.345624     0.512179  181
max min_per_class_accuracy   0.208558     0.785894  252
max mean_per_class_accuracy  0.21905      0.786882  246
max tns                      0.991528     100373    0
max fns                      0.991528     21017     0
max fps                      0.000480518  100380    399
max tps                      0.000480518  21017     399
max tnr                      0.991528     0.99993   0
max fnr                      0.991528     1         0
max fpr                      0.000480518  1         399
max tpr                      0.000480518  1         399

Gains/Lift Table: Avg response rate: 17.31 %, avg score: 17.57 %
group    cumulative_data_fraction    lower_threshold    lift       cumulative_lift    response_rate    score        cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain      cumulative_gain    kolmogorov_smirnov
-------  --------------------------  -----------------  ---------  -----------------  ---------------  -----------  --------------------------  ------------------  --------------  -------------------------  --------  -----------------  --------------------
1        0.0100002                   0.797524           4.66278    4.66278            0.807249         0.858535     0.807249                    0.858535            0.0466289       0.0466289                  366.278   366.278            0.0442978
2        0.0200005                   0.727952           4.81979    4.74128            0.834432         0.760232     0.82084                     0.809384            0.0481991       0.094828                   381.979   374.128            0.0904945
3        0.0300007                   0.674358           4.60092    4.6945             0.79654          0.700502     0.81274                     0.77309             0.0460104       0.140838                   360.092   369.45             0.134044
4        0.040001                    0.631739           4.47246    4.63899            0.7743           0.652639     0.80313                     0.742977            0.0447257       0.185564                   347.246   363.899            0.17604
5        0.0500012                   0.594927           4.26787    4.56476            0.73888          0.613232     0.79028                     0.717028            0.0426797       0.228244                   326.787   356.476            0.215562
6        0.100002                    0.460517           3.6265     4.09563            0.627842         0.522578     0.709061                    0.619803            0.181329        0.409573                   262.65    309.563            0.374387
7        0.150004                    0.36858            2.76626    3.65251            0.478913         0.412562     0.632345                    0.550723            0.138317        0.54789                    176.626   265.251            0.481193
8        0.200005                    0.306613           1.91554    3.21827            0.331631         0.336095     0.557166                    0.497066            0.0957796       0.643669                   91.5545   221.827            0.536556
9        0.299999                    0.217603           1.30473    2.58046            0.225884         0.258442     0.446745                    0.417529            0.130466        0.774135                   30.4733   158.046            0.573408
10       0.400002                    0.155544           0.735577   2.11923            0.127348         0.184693     0.366894                    0.359319            0.0735595       0.847695                   -26.4423  111.923            0.541429
11       0.500004                    0.110682           0.439633   1.7833             0.076112         0.13161      0.308737                    0.313776            0.0439644       0.891659                   -56.0367  78.3304            0.473658
12       0.599998                    0.0774394          0.26837    1.53083            0.0464618        0.0935804    0.265026                    0.277079            0.0268354       0.918495                   -73.163   53.0828            0.385181
13       0.700001                    0.0450547          0.241227   1.3466             0.0417628        0.0612108    0.233131                    0.24624             0.0241233       0.942618                   -75.8773  34.6595            0.293415
14       0.799995                    0.0104618          0.298347   1.21557            0.0516517        0.0275245    0.210447                    0.218902            0.029833        0.972451                   -70.1653  21.5571            0.208564
15       0.899998                    0.00175539         0.231236   1.1062             0.0400329        0.00445507   0.191512                    0.195074            0.0231241       0.995575                   -76.8764  10.6197            0.115589
16       1                           1.02312e-14        0.0442488  1                  0.00766063       0.000939867  0.173126                    0.17566             0.00442499      1                          -95.5751  0                  0

ModelMetricsBinomialGLM: glm
** Reported on cross-validation data. **

MSE: 0.1000499909569019
RMSE: 0.3163067987838736
LogLoss: 0.3381255694708556
AUC: 0.8552555599717258
AUCPR: 0.610807171226841
Gini: 0.7105111199434515
Null degrees of freedom: 566622
Residual degrees of freedom: 566598
Null deviance: 526483.071911141
Residual deviance: 383230.5310461157
AIC: 383280.5310461157

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.31851205003568933
       0       1       Error    Rate
-----  ------  ------  -------  ------------------
0      421654  45498   0.0974   (45498.0/467152.0)
1      37221   62250   0.3742   (37221.0/99471.0)
Total  458875  107748  0.146    (82719.0/566623.0)

Maximum Metrics: Maximum metrics at their respective thresholds
metric                       threshold    value     idx
---------------------------  -----------  --------  -----
max f1                       0.318512     0.600814  195
max f2                       0.188098     0.677165  264
max f0point5                 0.403188     0.62589   158
max accuracy                 0.403188     0.868583  158
max precision                0.699616     0.827448  56
max recall                   0.000520498  1         399
max specificity              0.989914     0.999931  0
max absolute_mcc             0.354557     0.515592  179
max min_per_class_accuracy   0.207938     0.782912  253
max mean_per_class_accuracy  0.230877     0.784973  240
max tns                      0.989914     467120    0
max fns                      0.989914     99466     0
max fps                      0.000520498  467152    399
max tps                      0.000520498  99471     399
max tnr                      0.989914     0.999931  0
max fnr                      0.989914     0.99995   0
max fpr                      0.000520498  1         399
max tpr                      0.000520498  1         399

Gains/Lift Table: Avg response rate: 17.56 %, avg score: 17.56 %
group    cumulative_data_fraction    lower_threshold    lift       cumulative_lift    response_rate    score       cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain      cumulative_gain    kolmogorov_smirnov
-------  --------------------------  -----------------  ---------  -----------------  ---------------  ----------  --------------------------  ------------------  --------------  -------------------------  --------  -----------------  --------------------
1        0.0100014                   0.795386           4.62182    4.62182            0.811364         0.854991    0.811364                    0.854991            0.0462245       0.0462245                  362.182   362.182            0.0439362
2        0.020001                    0.723676           4.77646    4.69914            0.83851          0.757459    0.824936                    0.80623             0.0477627       0.0939872                  377.646   369.914            0.0897402
3        0.0300005                   0.672108           4.66989    4.68939            0.819802         0.696599    0.823225                    0.769688            0.046697        0.140684                   366.989   368.939            0.134252
4        0.0400001                   0.629437           4.47083    4.63475            0.784857         0.650569    0.813633                    0.73991             0.0447065       0.185391                   347.083   363.475            0.176349
5        0.0500015                   0.591887           4.27001    4.5618             0.749603         0.610127    0.800826                    0.71395             0.0427059       0.228097                   327.001   356.18             0.216017
6        0.100001                    0.457401           3.58277    4.07229            0.628958         0.518988    0.714893                    0.616471            0.179138        0.407234                   258.277   307.229            0.372652
7        0.150001                    0.367399           2.80968    3.65143            0.493241         0.409802    0.64101                     0.547582            0.140483        0.547717                   180.968   265.143            0.482402
8        0.200001                    0.305723           1.89544    3.21243            0.332745         0.335286    0.563944                    0.494509            0.0947713       0.642489                   89.5437   221.243            0.536707
9        0.3                         0.217616           1.26922    2.5647             0.222812         0.258292    0.450234                    0.41577             0.126921        0.76941                    26.9221   156.47             0.569362
10       0.4                         0.156255           0.756204   2.11258            0.132752         0.185408    0.370864                    0.35818             0.07562         0.84503                    -24.3796  111.258            0.539791
11       0.500001                    0.111676           0.460832   1.78222            0.0808994        0.132612    0.312871                    0.313066            0.0460838       0.891114                   -53.9168  78.2225            0.474393
12       0.6                         0.0777814          0.282295   1.53224            0.049557         0.0942696   0.268985                    0.2766              0.0282293       0.919343                   -71.7705  53.2238            0.387341
13       0.7                         0.0456897          0.233637   1.34672            0.0410151        0.061657    0.236418                    0.245894            0.0233636       0.942707                   -76.6363  34.6725            0.294387
14       0.799999                    0.0114722          0.311851   1.21737            0.0547457        0.0286151   0.213709                    0.218734            0.031185        0.973892                   -68.8149  21.7366            0.21092
15       0.899999                    0.00187825         0.210314   1.10547            0.0369207        0.00482415  0.194066                    0.194967            0.0210313       0.994923                   -78.9686  10.5472            0.115137

In [15]:
print("Optimal Threshold:", optimal_threshold)
print("Validation F1 Score:", valid_f1)
print("Test F1 Score:", test_f1)

Optimal Threshold: 0.5
Validation F1 Score: 0.47790802524797116
Test F1 Score: 0.4729967104212578

In [ ]:
#H20-GLM did not perform well on encoded data it has validation f1 and test f1 score less than 0.5 so it is better to use logistic regression.

## Model Tuning

Chooseing one model from the above list.Performing tuning for the selected model:
- Hyper-parameter tuning. Your hyper-parameter search space should have at least 50 combinations.
- To avoid overfitting and provide you with reasonable estimate of model performance on hold-out dataset, you will need to split your dataset as following:
    - Train, will be used to train model
    - Validation, will be used to validate model each round of training
    - Testing, will be used to provide final performance metrics, used only once on the final model
- Feature engineering.
**Selelct final model that produces best performance on the Test dataset.**
- For the best model, calculate probability threshold to maximize F1.

In [16]:
df1=df.copy()
#Feature Engineering
#df["Years_of_Term"]=round((df1["Term"]/12),4)#Number of years the loan term is.
df["Employment_Growth"]=round((df1["CreateJob"]-df1["RetainedJob"]),4)#Net employment growth rate.
df["Is_Franchise"]=round((df1["FranchiseCode"].apply(lambda x: 1 if x>1 else 0)),4)#Is bank a franchise or not
df["Employment_Opportunity"]=round((df1["NoEmp"]*df1["NewExist"]))#Number of new employment opportunies created
#df['StateSame'] = (df1["State"]==df1["BankState"]).astype(int)#If the loan dibusred business and the bank are in the same state.
df['SBA_AppvPct'] = df1['SBA_Appv'] / df1['GrAppv']#SBA_Appv/GrAppv
df['AppvDisbursed'] = (df1["DisbursementGross"]==df1["GrAppv"]).astype(int)#if DisbursementGross is equal to Grapproved
df["RevLinecredit"]=round((df1["RevLineCr"].apply(lambda x:1 if x=="Y" else 0)),4)#Does the company has revolving line of credit
df["Employees_more_than_10"]= (df1['NoEmp'] > 10).astype(int)#does the company has more than 10 employees or not
df["GrAppv_more_than100k"]=  (df1["GrAppv"]>100000).astype(int)#Does the Grappv has more than 100k$ or not.

In [17]:
#we used a dataset that is not encoded to do feature engineering as there are categorical variables now we need to encode again for logistic regression
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
# Initialize OneHotEncoder
ohe = OneHotEncoder()
# Fit and transform the categorical column using OneHotEncoder
ohe_results = ohe.fit_transform(df[['LowDoc']]).toarray()
# Create a new dataframe with the encoded columns
encoded_data = pd.DataFrame(ohe_results, columns=ohe.get_feature_names(['LowDoc']))
# Concatenate the original dataframe with the encoded dataframe
data_encoded = pd.concat([df, encoded_data], axis=1)
# Drop the original categorical column
data_encoded.drop(['LowDoc'], axis=1, inplace=True)
df=data_encoded

#Target encoding
import category_encoders as ce
target_cols = [col for col in df.columns if df[col].dtype=='object' and col !="LowDoc" and col != 'MIS_Status']
target_encoder = ce.TargetEncoder(cols=target_cols)
df = target_encoder.fit_transform(df, df['MIS_Status'])
df['MIS_Status'] = df.pop('MIS_Status')

In [18]:
df.head()

,index,City,State,Zip,Bank,BankState,NAICS,Term,NoEmp,NewExist,CreateJob,RetainedJob,FranchiseCode,UrbanRural,RevLineCr,DisbursementGross,BalanceGross,GrAppv,SBA_Appv,Years_of_Term,Employment_Growth,Is_Franchise,Employment_Opportunity,StateSame,SBA_AppvPct,AppvDisbursed,RevLinecredit,Employees_more_than_10,GrAppv_more_than100k,LowDoc_0,LowDoc_1,LowDoc_A,LowDoc_C,LowDoc_N,LowDoc_R,LowDoc_S,LowDoc_Y,MIS_Status
0,0,0.172222,0.197566,21060,0.000000,0.382373,811111,240,7,1.0,6,7,1,1,0.149590,743000.0,0.0,743000.0,743000.0,20.0,-1,0,7.0,0,1.000,1,0,0,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0
1,1,0.118343,0.123196,53095,0.273809,0.222215,722410,240,20,1.0,0,0,1,0,0.145047,137000.0,0.0,137000.0,109737.0,20.0,0,0,20.0,0,0.801,1,0,1,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0
2,2,0.149938,0.184597,92128,0.268160,0.180539,0,120,2,1.0,0,0,1,0,0.149590,280000.0,0.0,280000.0,210000.0,10.0,0,0,2.0,0,0.750,1,0,0,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0
3,3,0.139818,0.128058,1570,0.037564,0.065488,621310,84,7,1.0,0,0,1,1,0.149590,144500.0,0.0,144500.0,122825.0,7.0,0,0,7.0,1,0.850,1,0,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0
4,4,0.178832,0.153553,64804,0.174985,0.158467,0,60,2,2.0,0,0,1,0,0.145047,52500.0,0.0,52500.0,42000.0,5.0,0,0,4.0,0,0.800,1,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0

In [19]:
from sklearn.preprocessing import StandardScaler
#Splitting the data into x and y
X_data= df.drop(columns=data.columns[-1])
y_data= df.iloc[:, -1:]
#Splliting the data
from sklearn.model_selection import train_test_split
# Split the data into training and testing sets (70/30 split)
X_train, X_test, y_train, y_test = train_test_split(X_data, y_data, test_size=0.3, random_state=42)
# Split the training data into training and validation sets (85/15 split)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.15, random_state=42)

#Scaling the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_val=scaler.transform(X_val)

In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score, precision_recall_curve, roc_curve
import numpy as np
from sklearn.model_selection import RandomizedSearchCV


# define the logistic regression model
logreg = LogisticRegression()

# define the search space for hyperparameters
param_dist = {'penalty': ['l1', 'l2', 'elasticnet', 'none'],
              'C': [0.001, 0.01, 0.1, 1, 10, 100],
              'fit_intercept': [True, False],
              'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'],
              'max_iter': [50, 100, 150, 200, 250],
              'l1_ratio': [0.1, 0.3, 0.5, 0.7, 0.9],
              'tol': [0.0001, 0.001, 0.01, 0.1, 1]}

# define the randomized search object
search = RandomizedSearchCV(logreg, param_distributions=param_dist, 
                            n_iter=500, cv=5, scoring='f1_macro', n_jobs=-1)

# fit the randomized search object to the data
search.fit(X_train, y_train)

# get the best hyperparameters and corresponding f1 score
best_params = search.best_params_
best_score = search.best_score_

# train the logistic regression model with the best hyperparameters
best_logreg = LogisticRegression(**best_params)
best_logreg.fit(X_train, y_train)

LogisticRegression(C=1, l1_ratio=0.1, max_iter=50, penalty='none', tol=0.001)

In [21]:
# generate predictions on the validation data
y_val_pred_proba = best_logreg.predict_proba(X_val)[:,1]
precision, recall, thresholds = precision_recall_curve(y_val, y_val_pred_proba)
f1_scores = 2*(precision*recall)/(precision+recall)
optimal_idx = np.argmax(f1_scores)
optimal_threshold = thresholds[optimal_idx]

y_val_pred = (y_val_pred_proba >= optimal_threshold).astype(int)

# calculate the f1 score on the validation data
f1_val = f1_score(y_val, y_val_pred,average='macro')

# generate predictions on the test data
y_test_pred_proba = best_logreg.predict_proba(X_test)[:,1]
y_test_pred = (y_test_pred_proba >= optimal_threshold).astype(int)

# calculate the f1 score on the test data
f1_test = f1_score(y_test, y_test_pred,average='macro')

# evaluate the best model on the test data
accuracy_test = best_logreg.score(X_test, y_test)

print("Best hyperparameters: ", best_params)
print("Best f1 score: ", best_score)
print("F1 score on validation data: ", f1_val)
print("F1 score on test data: ", f1_test)
print("Accuracy on test data: ", accuracy_test)
print("Optimal threshold: ", optimal_threshold)

Best hyperparameters:  {'tol': 0.001, 'solver': 'lbfgs', 'penalty': 'none', 'max_iter': 50, 'l1_ratio': 0.1, 'fit_intercept': True, 'C': 1}
Best f1 score:  0.7282786240253983
F1 score on validation data:  0.7718689707934436
F1 score on test data:  0.7715913660514206
Accuracy on test data:  0.873281845330038
Optimal threshold:  0.31995216264432313

In [ ]:
#From the above models h2o glm and logistic regression logistic regression performed with differen types of regulations I used randaom search for best hyperparameters.
#for the best model the obtained Best F1 score is shown above and obtained optimal thresold is 0.31.

## Save all artifacts

Saving all artifacts needed for scoring function:
- Trained model
- Encoders
- Any other arficats you will need for scoring

In [22]:
import pickle

ohe_encoder = ce.OneHotEncoder(cols="LowDoc", use_cat_names=True)
data = ohe_encoder.fit_transform(do)

target_encoder = ce.TargetEncoder(cols=target_cols)
data = target_encoder.fit_transform(do, do['MIS_Status'])

artifacts4 = {
    "model": best_logreg,
    "target_encoder": target_encoder,
    "ohe_encoder": ohe_encoder,
    "scaler": scaler,
}

# save all the artifacts
with open('artifacts4.pkl', 'wb') as f:
    pickle.dump(artifacts4, f)

# open the file again
with open('artifacts4.pkl', 'rb') as f:
    artifacts4 = pickle.load(f)